# Generated by Django 6.0.6 on 2026-08-23 14:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=accounts.models.generate_otp, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default=accounts.models.generate_otp, max_length=6, unique=True),
        ),
    ]
