# Generated by Django 6.0.6 on 2026-06-17 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='current_streak',
            new_name='course_current_streak',
        ),
        migrations.RenameField(
            model_name='streak',
            old_name='longest_streak',
            new_name='course_longest_streak',
        ),
        migrations.RenameField(
            model_name='streak',
            old_name='last_activity_date',
            new_name='last_course_activity_date',
        ),
        migrations.AddField(
            model_name='streak',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 17, 6, 40, 14, 508559, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streak',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='login_current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streak',
            name='login_longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
